[build]
pythonVersion = "3.11"  # Adjust if using a different version
preInstall = "pip install --upgrade pip"
nixpacksPlan = { 
  providers = ["python"],
  packages = ["cairo.dev", "pkg-config", "pango.dev", "gcc", "ffmpeg", "glib.dev", "gdk-pixbuf.dev", "libffi.dev", "pixman.dev", "python311Packages.setuptools"] 
}

[deploy]
startCommand = "chainlit run app.py --host 0.0.0.0 --port $PORT"
